hyperion/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :financiamentos
  match 'financiamentos/:id/aceita', controller: 'financiamentos', action: 'aceita', via: 'get'
  match 'financiamentos/:id/recusa', controller: 'financiamentos', action: 'recusa', via: 'get'
  resources :imovels
  resources :clientes
  resources :simulacao do
    get 'index', :on => :collection
  end
  
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  root 'sessions#new'

end

hyperion/app/models/cliente.rb
class Cliente < ActiveRecord::Base
	validates_uniqueness_of :cpf
	validates :cpf, format: { with: /\d{3}.\d{3}\.\d{3}\-\d{2}/, message: "inválido! Escreva no formato XXX.XXX.XXX-XX"}
	has_many :financiamento, :dependent => :destroy
end

hyperion/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente destruido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:cpf, :nome, :idade, :renda)
    end
end

hyperion/app/helpers/clientes_helper.rb
module ClientesHelper
end

hyperion/app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :renda %><br>
    <%= f.text_field :renda %>
  </div>
  <div class="actions">
    <%= f.submit "Criar cliente"%>
  </div>
<% end %>

hyperion/app/views/clientes/edit.html.erb
<div class="edit--clientes">
<h1>Atualizando Cliente</h1>
<%= render 'form' %>

<table>
	<th class="botao botao--novo">
	<%= link_to 'Detalhes', @cliente %> </th> 
	<th class="botao botao--novo">
	<%= link_to 'Voltar', clientes_path %></th>
</table>
</div>

hyperion/app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Clientes</h1>

<table>
  <thead>
    <tr>
      <th class="id">Cpf</th>
      <th>Nome</th>
      <th>Idade</th>
      <th>Renda</th>
      <th class="noborder" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td class="id"><%= cliente.cpf %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.idade %></td>
        <td>R$ <%= cliente.renda %></td>
        <td class="botao"><%= link_to 'Detalhes', cliente %></td>
        <td class="botao"><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td class="botao"><%= link_to 'Destruir', cliente, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="botao botao--novo">
  <%= link_to 'Novo Cliente', new_cliente_path %>
</div>

hyperion/app/views/clientes/new.html.erb
<div class="new--clientes">
<h1>Novo Cliente</h1>

<%= render 'form' %>
<table style="margin-left:15%;">
<th class="botao botao--novo">
	<%= link_to 'Voltar', clientes_path %></th>
</table>
</div>

hyperion/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show--clientes">
<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @cliente.idade %>
</p>

<p>
  <strong>Renda:</strong>
  R$ <%= @cliente.renda %>
</p>

<table>
	<th class="botao botao--novo">
	<%= link_to 'Editar', edit_cliente_path(@cliente) %> </th> 
	<th class="botao botao--novo">
	<%= link_to 'Voltar', clientes_path %></th>
</table>

</div>