hyperion/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :financiamentos
  match 'financiamentos/:id/aceita', controller: 'financiamentos', action: 'aceita', via: 'get'
  match 'financiamentos/:id/recusa', controller: 'financiamentos', action: 'recusa', via: 'get'
  resources :imovels
  resources :clientes
  resources :simulacao do
    get 'index', :on => :collection
  end
  
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  root 'sessions#new'

end

hyperion/app/models/financiamento.rb
class Financiamento < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :imovel
end

hyperion/app/controllers/financiamentos_controller.rb
class FinanciamentosController < ApplicationController
  before_action :set_financiamento, only: [:show, :edit, :update, :destroy, :aceita, :recusa]

  # GET /financiamentos
  # GET /financiamentos.json
  def index
    @financiamentos = Financiamento.all
  end

  def aceita
    @financiamento.status = "ACEITO"
    @financiamento.save

    respond_to do |format|
        format.html { redirect_to @financiamento, notice: 'Financiamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @financiamento }
    end
  end

  def recusa
    @financiamento.status = "NAO_ACEITO"
    @financiamento.save

    respond_to do |format|
        format.html { redirect_to @financiamento, notice: 'Financiamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @financiamento }
    end
  end

  # GET /financiamentos/1
  # GET /financiamentos/1.json
  def show
  end

  # GET /financiamentos/new
  def new
    @financiamento = Financiamento.new
    @cliente = Cliente.all
    @imovel = Imovel.all
  end

  # GET /financiamentos/1/edit
  def edit
  end

  # POST /financiamentos
  # POST /financiamentos.json
  def create
    @financiamento = Financiamento.new(financiamento_params)
    cliente = Cliente.find(@financiamento.cliente_id)
    imovel = Imovel.find(@financiamento.imovel_id)
    if(cliente.idade < 18 or cliente.idade >= 65)
      @financiamento.status = "NEGADO"
      @financiamento.meses = nil
    elsif(cliente.renda < 500.00 or cliente.renda > 3499.99)
      @financiamento.status = "NEGADO"
      @financiamento.meses = nil
    elsif(imovel.valor > 180000.00)
      @financiamento.status = "NEGADO"
      @financiamento.meses = nil
    else
      @financiamento.entrada = (cliente.renda * 5).round(2)
      if(cliente.idade >= 18 and cliente.idade < 26) 
        percentual_idade = 0.03
      elsif(cliente.idade >= 26 and cliente.idade < 35)
        percentual_idade = 0.025
      else
        percentual_idade = 0.02
      end
      if(cliente.renda >= 500.00 and cliente.renda < 1500.00) 
        percentual_renda = 0.03
        @financiamento.juros = 0.02
      elsif(cliente.renda >= 1500.00 and cliente.renda < 2500.00)
        percentual_renda = 0.025
        @financiamento.juros = 0.015
      else
        percentual_renda = 0.015
        @financiamento.juros = 0.01
      end
      @financiamento.subsidio = ((percentual_renda + percentual_idade)* imovel.valor).round(2)
      @financiamento.parcela = (((imovel.valor - @financiamento.subsidio - @financiamento.subsidio) *
      (1 + @financiamento.juros**(Integer(@financiamento.meses/12))))/@financiamento.meses).round(2)
      if(@financiamento.parcela > (cliente.renda/2))
        @financiamento.status = "INVIAVEL"
      else
        @financiamento.status = "SIMULACAO"
      end
      @financiamento.save
    end

    respond_to do |format|
      if @financiamento.save
        format.html { redirect_to @financiamento, notice: 'Financiamento was successfully created.' }
        format.json { render :show, status: :created, location: @financiamento }
      else
        format.html { render :new }
        format.json { render json: @financiamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financiamentos/1
  # PATCH/PUT /financiamentos/1.json
  def update
    respond_to do |format|
      if @financiamento.update(financiamento_params)
        format.html { redirect_to @financiamento, notice: 'Financiamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @financiamento }
      else
        format.html { render :edit }
        format.json { render json: @financiamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financiamentos/1
  # DELETE /financiamentos/1.json
  def destroy
    @financiamento.destroy
    respond_to do |format|
      format.html { redirect_to financiamentos_url, notice: 'Financiamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financiamento
      @financiamento = Financiamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def financiamento_params
      params.require(:financiamento).permit(:cliente_id, :imovel_id, :juros, :parcela, :entrada, :subsidio, :status, :meses)
    end
end

hyperion/app/helpers/financiamentos_helper.rb
module FinanciamentosHelper
end

hyperion/app/views/financiamentos/_form.html.erb
<%= form_for(@financiamento) do |f| %>
  <% if @financiamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@financiamento.errors.count, "error") %> prohibited this financiamento from being saved:</h2>

      <ul>
      <% @financiamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente_id %><br>
    <%= f.text_field :cliente_id %>
  </div>
  <div class="field">
    <%= f.label :imovel_id %><br>
    <%= f.text_field :imovel_id %>
  </div>
  <div class="field">
    <%= f.label :juros %><br>
    <%= f.text_field :juros %>
  </div>
  <div class="field">
    <%= f.label :parcela %><br>
    <%= f.text_field :parcela %>
  </div>
  <div class="field">
    <%= f.label :entrada %><br>
    <%= f.text_field :entrada %>
  </div>
  <div class="field">
    <%= f.label :subsidio %><br>
    <%= f.text_field :subsidio %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :meses %><br>
    <%= f.text_field :meses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hyperion/app/views/financiamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Financiamentos</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Imovel</th>
      <th>Juros</th>
      <th>Parcela (R$)</th>
      <th>Entrada (R$)</th>
      <th>Subsidio (R$)</th>
      <th>Status</th>
      <th>Meses</th>
      <th class="noborder" colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @financiamentos.each do |financiamento| %>
      <tr>
        <td><%= Cliente.find(financiamento.cliente_id).nome %></td>
        <td><%= Imovel.find(financiamento.imovel_id).nome %></td>
        <td><%= financiamento.juros %></td>
        <td><%= financiamento.parcela %></td>
        <td><%= financiamento.entrada %></td>
        <td><%= financiamento.subsidio %></td>
        <% case financiamento.status 
        when "SIMULACAO"%><td class="simulacao"><%= financiamento.status %></td>
        <% when "NEGADO" %><td class="negado"><%= financiamento.status %></td>
        <% when "INVIAVEL" %><td class="inviavel"><%= financiamento.status %></td>
        <% when "ACEITO" %><td class="aceito"><%= financiamento.status %></td>
        <% when "NAO_ACEITO" %><td class="nao_aceito"><%= financiamento.status %></td>
        <% end %>
        <td><%= financiamento.meses %></td>
        
        <% if financiamento.status == "SIMULACAO"%>
          <td class="botao--acc"><%= link_to 'Aceitar', controller: "financiamentos", action: "aceita", id: financiamento, data: {confirm: 'Tem certeza?'} %></td>
          <td class="botao--rec"><%= link_to 'Recusar', controller: "financiamentos", action: "recusa", id: financiamento, data: {confirm: 'Tem certeza?'} %></td>
        <% else %>
          <td class="noborder" colspan="2"></td>
        <% end %>
        <td class="botao"><%= link_to 'Detalhes', financiamento %></td>
        <td class="botao"><%= link_to 'Destruir', financiamento, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="botao botao--novo">
  <%= link_to 'Simulação', simulacao_index_path %>
</div>

hyperion/app/views/financiamentos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show--financiamento">
<p>
  <strong>Cliente:</strong>
  <%= Cliente.find(@financiamento.cliente_id).nome %>
</p>

<p>
  <strong>Imovel:</strong>
  <%= Imovel.find(@financiamento.imovel_id).nome %>
</p>

<p>
  <strong>Juros:</strong>
  <%= @financiamento.juros %>
</p>

<p>
  <strong>Parcela:</strong>
  R$ <%= @financiamento.parcela %>
</p>

<p>
  <strong>Entrada:</strong>
  R$ <%= @financiamento.entrada %>
</p>

<p>
  <strong>Subsidio:</strong>
  R$ <%= @financiamento.subsidio %>
</p>

<p>
  <strong>Status:</strong>
  <%= @financiamento.status %>
</p>

<p>
  <strong>Meses:</strong>
  <%= @financiamento.meses %>
</p>

<table>
  <th class="botao botao--novo">
  <%= link_to 'Voltar', financiamentos_path %></th>
</table>
</div>