hyperion/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :financiamentos
  match 'financiamentos/:id/aceita', controller: 'financiamentos', action: 'aceita', via: 'get'
  match 'financiamentos/:id/recusa', controller: 'financiamentos', action: 'recusa', via: 'get'
  resources :imovels
  resources :clientes
  resources :simulacao do
    get 'index', :on => :collection
  end
  
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  root 'sessions#new'

end

hyperion/app/models/imovel.rb
class Imovel < ActiveRecord::Base
    has_many :financiamento, :dependent => :destroy
end

hyperion/app/controllers/imovels_controller.rb
class ImovelsController < ApplicationController
  before_action :set_imovel, only: [:show, :edit, :update, :destroy]

  # GET /imovels
  # GET /imovels.json
  def index
    @imovels = Imovel.all
  end

  # GET /imovels/1
  # GET /imovels/1.json
  def show
  end

  # GET /imovels/new
  def new
    @imovel = Imovel.new
  end

  # GET /imovels/1/edit
  def edit
  end

  # POST /imovels
  # POST /imovels.json
  def create
    @imovel = Imovel.new(imovel_params)

    respond_to do |format|
      if @imovel.save
        format.html { redirect_to @imovel, notice: 'Imóvel criado com sucesso.' }
        format.json { render :show, status: :created, location: @imovel }
      else
        format.html { render :new }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imovels/1
  # PATCH/PUT /imovels/1.json
  def update
    respond_to do |format|
      if @imovel.update(imovel_params)
        format.html { redirect_to @imovel, notice: 'Imóvel atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @imovel }
      else
        format.html { render :edit }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imovels/1
  # DELETE /imovels/1.json
  def destroy
    @imovel.destroy
    respond_to do |format|
      format.html { redirect_to imovels_url, notice: 'Imóvel destruido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imovel
      @imovel = Imovel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imovel_params
      params.require(:imovel).permit(:nome, :unidade, :valor)
    end
end

hyperion/app/helpers/imovels_helper.rb
module ImovelsHelper
end

hyperion/app/views/imovels/_form.html.erb
<%= form_for(@imovel) do |f| %>
  <% if @imovel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imovel.errors.count, "error") %> prohibited this imovel from being saved:</h2>

      <ul>
      <% @imovel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :unidade %><br>
    <%= f.number_field :unidade %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit "Criar imóvel"%>
  </div>
<% end %>

hyperion/app/views/imovels/edit.html.erb
<div class="edit--imovel">
<h1>Atualizando Imóvel</h1>

<%= render 'form' %>

<table>
	<th class="botao botao--novo">
	<%= link_to 'Detalhes', @imovels %> </th> 
	<th class="botao botao--novo">
	<%= link_to 'Voltar', imovels_path %></th>
</table>
</div>

hyperion/app/views/imovels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Imóveis</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Unidade</th>
      <th>Valor</th>
      <th class="noborder"  colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imovels.each do |imovel| %>
      <tr>
        <td><%= imovel.nome %></td>
        <td><%= imovel.unidade %></td>
        <td>R$ <%= imovel.valor %></td>
        <td class="botao"><%= link_to 'Detalhes', imovel %></td>
        <td class="botao"><%= link_to 'Editar', edit_imovel_path(imovel) %></td>
        <td class="botao"><%= link_to 'Destruir', imovel, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="botao botao--novo">
  <%= link_to 'Novo Imóvel', new_imovel_path %>
</div>

hyperion/app/views/imovels/new.html.erb
<div class="new--imovel">
<h1>Novo Imóvel</h1>

<%= render 'form' %>

<table style="margin-left:17%;">
<th class="botao botao--novo">
	<%= link_to 'Voltar', imovels_path %></th>
</table>

</div>

hyperion/app/views/imovels/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show--imovel">
<p>
  <strong>Nome:</strong>
  <%= @imovel.nome %>
</p>

<p>
  <strong>Unidade:</strong>
  <%= @imovel.unidade %>
</p>

<p>
  <strong>Valor:</strong>
  R$ <%= @imovel.valor %>
</p>

<table>
	<th class="botao botao--novo">
	<%= link_to 'Editar', edit_imovel_path(@imovel) %> </th> 
	<th class="botao botao--novo">
	<%= link_to 'Voltar', imovels_path %></th>
</table>
</div>