hyperion/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :financiamentos
  match 'financiamentos/:id/aceita', controller: 'financiamentos', action: 'aceita', via: 'get'
  match 'financiamentos/:id/recusa', controller: 'financiamentos', action: 'recusa', via: 'get'
  resources :imovels
  resources :clientes
  resources :simulacao do
    get 'index', :on => :collection
  end
  
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  root 'sessions#new'

end

hyperion/app/views/layouts/_header.html.erb
<div class="wrapper-header">
  <header>
    <div>
      <nav>
      	  <div class="aba"><%=image_tag("hyperion.png", height: '32', width: '200')=%></div>
      	  <% if logged_in? %>
            <div class="aba"><%= link_to 'Clientes', clientes_path %></div>
            <div class="aba"><%= link_to 'Imóveis', imovels_path %></div>
            <div class="aba"><%= link_to 'Financiamentos', financiamentos_path %></div>
            <div class="aba"><%= link_to 'Simulação', controller: "simulacao", action: "index"%></div>
            <div class="aba"><%= link_to "Log out", sign_out_path, method: "delete" %></div>
          <% else %>
            <div class="aba"><%= link_to "Log in", root_path %></div>
          <% end %>

      </nav>
    </div>
  </header>
</div>

hyperion/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hyperion</title>
  <%=favicon_link_tag("icon.ico")%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="wrapper">
	<div class="content">
		<%= yield %>
	</div>
</div>


</body>
</html>